// Book mapping for Old and New Testament
export const bookMapping = {
  oldTestament: [
    { order: 1, slug: "genesis", english: "Genesis", telugu: "ఆదికాండము" },
    { order: 2, slug: "exodus", english: "Exodus", telugu: "నిర్గమకాండము" },
    { order: 3, slug: "leviticus", english: "Leviticus", telugu: "లేవీయకాండము" },
    { order: 4, slug: "numbers", english: "Numbers", telugu: "సంఖ్యాకాండము" },
    { order: 5, slug: "deuteronomy", english: "Deuteronomy", telugu: "ద్వితియోపదేశకాండము" },
    { order: 6, slug: "joshua", english: "Joshua", telugu: "యెహోషువ" },
    { order: 7, slug: "judges", english: "Judges", telugu: "న్యాయాధిపతులు" },
    { order: 8, slug: "ruth", english: "Ruth", telugu: "రూతు" },
    { order: 9, slug: "1-samuel", english: "1 Samuel", telugu: "1సమూయేలు" },
    { order: 10, slug: "2-samuel", english: "2 Samuel", telugu: "2సమూయేలు" },
    { order: 11, slug: "1-kings", english: "1 Kings", telugu: "1రాజులు" },
    { order: 12, slug: "2-kings", english: "2 Kings", telugu: "2రాజులు" },
    { order: 13, slug: "1-chronicles", english: "1 Chronicles", telugu: "1దినవృత్తాంతములు" },
    { order: 14, slug: "2-chronicles", english: "2 Chronicles", telugu: "2దినవృత్తాంతములు" },
    { order: 15, slug: "ezra", english: "Ezra", telugu: "ఎజ్రా" },
    { order: 16, slug: "nehemiah", english: "Nehemiah", telugu: "నెహెమ్యా" },
    { order: 17, slug: "esther", english: "Esther", telugu: "ఎస్తేరు" },
    { order: 18, slug: "job", english: "Job", telugu: "యోబు" },
    { order: 19, slug: "psalms", english: "Psalms", telugu: "కీర్తనలు" },
    { order: 20, slug: "proverbs", english: "Proverbs", telugu: "సామెతలు" },
    { order: 21, slug: "ecclesiastes", english: "Ecclesiastes", telugu: "ప్రసంగి" },
    { order: 22, slug: "song-of-solomon", english: "Song of Solomon", telugu: "పరమగీతము" },
    { order: 23, slug: "isaiah", english: "Isaiah", telugu: "యెషయా" },
    { order: 24, slug: "jeremiah", english: "Jeremiah", telugu: "యిర్మియా" },
    { order: 25, slug: "lamentations", english: "Lamentations", telugu: "విలాపవాక్యములు" },
    { order: 26, slug: "ezekiel", english: "Ezekiel", telugu: "యెహేజ్కేలు" },
    { order: 27, slug: "daniel", english: "Daniel", telugu: "దానియేలు" },
    { order: 28, slug: "hosea", english: "Hosea", telugu: "హోషేయా" },
    { order: 29, slug: "joel", english: "Joel", telugu: "యోవేలు" },
    { order: 30, slug: "amos", english: "Amos", telugu: "ఆమోసు" },
    { order: 31, slug: "obadiah", english: "Obadiah", telugu: "ఓబద్యా" },
    { order: 32, slug: "jonah", english: "Jonah", telugu: "యోనా" },
    { order: 33, slug: "micah", english: "Micah", telugu: "మీకా" },
    { order: 34, slug: "nahum", english: "Nahum", telugu: "నహూము" },
    { order: 35, slug: "habakkuk", english: "Habakkuk", telugu: "హబక్కూకు" },
    { order: 36, slug: "zephaniah", english: "Zephaniah", telugu: "జెఫన్యా" },
    { order: 37, slug: "haggai", english: "Haggai", telugu: "హగ్గయి" },
    { order: 38, slug: "zechariah", english: "Zechariah", telugu: "జెకర్యా" },
    { order: 39, slug: "malachi", english: "Malachi", telugu: "మలాకీ" }
  ],
  newTestament: [
    { order: 1, slug: "matthew", english: "Matthew", telugu: "మత్తయి" },
    { order: 2, slug: "mark", english: "Mark", telugu: "మార్కు" },
    { order: 3, slug: "luke", english: "Luke", telugu: "లూకా" },
    { order: 4, slug: "john", english: "John", telugu: "యోహాను" },
    { order: 5, slug: "acts", english: "Acts", telugu: "అపో.కార్యములు" },
    { order: 6, slug: "romans", english: "Romans", telugu: "రోమీయులకు" },
    { order: 7, slug: "1-corinthians", english: "1 Corinthians", telugu: "1కోరింథీయులకు" },
    { order: 8, slug: "2-corinthians", english: "2 Corinthians", telugu: "2కోరింథీయులకు" },
    { order: 9, slug: "galatians", english: "Galatians", telugu: "గలతియులకు" },
    { order: 10, slug: "ephesians", english: "Ephesians", telugu: "ఎఫెసీయులకు" },
    { order: 11, slug: "philippians", english: "Philippians", telugu: "ఫిలిప్పీయులకు" },
    { order: 12, slug: "colossians", english: "Colossians", telugu: "కొలస్సీయులకు" },
    { order: 13, slug: "1-thessalonians", english: "1 Thessalonians", telugu: "1థెస్సలొనికయులకు" },
    { order: 14, slug: "2-thessalonians", english: "2 Thessalonians", telugu: "2థెస్సలొనికయులకు" },
    { order: 15, slug: "1-timothy", english: "1 Timothy", telugu: "1తిమోతికి" },
    { order: 16, slug: "2-timothy", english: "2 Timothy", telugu: "2తిమోతికి" },
    { order: 17, slug: "titus", english: "Titus", telugu: "తీతుకు" },
    { order: 18, slug: "philemon", english: "Philemon", telugu: "ఫిలేమోనుకు" },
    { order: 19, slug: "hebrews", english: "Hebrews", telugu: "హెబ్రీయులకు" },
    { order: 20, slug: "james", english: "James", telugu: "యాకోబు" },
    { order: 21, slug: "1-peter", english: "1 Peter", telugu: "1పేతురు" },
    { order: 22, slug: "2-peter", english: "2 Peter", telugu: "2పేతురు" },
    { order: 23, slug: "1-john", english: "1 John", telugu: "1యోహాను" },
    { order: 24, slug: "2-john", english: "2 John", telugu: "2యోహాను" },
    { order: 25, slug: "3-john", english: "3 John", telugu: "3యోహాను" },
    { order: 26, slug: "jude", english: "Jude", telugu: "యూదా" },
    { order: 27, slug: "revelation-of-john", english: "Revelation", telugu: "ప్రకటన గ్రంథం" }
  ]
};

