export const BIBLE_BOOKS = [
    { order: 1, name: "Genesis", abbreviation: "Gen", testament: "OT" },
    { order: 2, name: "Exodus", abbreviation: "Exod", testament: "OT" },
    { order: 3, name: "Leviticus", abbreviation: "Lev", testament: "OT" },
    { order: 4, name: "Numbers", abbreviation: "Num", testament: "OT" },
    { order: 5, name: "Deuteronomy", abbreviation: "Deut", testament: "OT" },
    { order: 6, name: "Joshua", abbreviation: "Josh", testament: "OT" },
    { order: 7, name: "Judges", abbreviation: "Judg", testament: "OT" },
    { order: 8, name: "Ruth", abbreviation: "Ruth", testament: "OT" },
    { order: 9, name: "1 Samuel", abbreviation: "1Sam", testament: "OT" },
    { order: 10, name: "2 Samuel", abbreviation: "2Sam", testament: "OT" },
    { order: 11, name: "1 Kings", abbreviation: "1Kgs", testament: "OT" },
    { order: 12, name: "2 Kings", abbreviation: "2Kgs", testament: "OT" },
    { order: 13, name: "1 Chronicles", abbreviation: "1Chr", testament: "OT" },
    { order: 14, name: "2 Chronicles", abbreviation: "2Chr", testament: "OT" },
    { order: 15, name: "Ezra", abbreviation: "Ezra", testament: "OT" },
    { order: 16, name: "Nehemiah", abbreviation: "Neh", testament: "OT" },
    { order: 17, name: "Esther", abbreviation: "Esth", testament: "OT" },
    { order: 18, name: "Job", abbreviation: "Job", testament: "OT" },
    { order: 19, name: "Psalms", abbreviation: "Ps", testament: "OT" },
    { order: 20, name: "Proverbs", abbreviation: "Prov", testament: "OT" },
    { order: 21, name: "Ecclesiastes", abbreviation: "Eccl", testament: "OT" },
    { order: 22, name: "Song of Solomon", abbreviation: "Song", testament: "OT" },
    { order: 23, name: "Isaiah", abbreviation: "Isa", testament: "OT" },
    { order: 24, name: "Jeremiah", abbreviation: "Jer", testament: "OT" },
    { order: 25, name: "Lamentations", abbreviation: "Lam", testament: "OT" },
    { order: 26, name: "Ezekiel", abbreviation: "Ezek", testament: "OT" },
    { order: 27, name: "Daniel", abbreviation: "Dan", testament: "OT" },
    { order: 28, name: "Hosea", abbreviation: "Hos", testament: "OT" },
    { order: 29, name: "Joel", abbreviation: "Joel", testament: "OT" },
    { order: 30, name: "Amos", abbreviation: "Amos", testament: "OT" },
    { order: 31, name: "Obadiah", abbreviation: "Obad", testament: "OT" },
    { order: 32, name: "Jonah", abbreviation: "Jonah", testament: "OT" },
    { order: 33, name: "Micah", abbreviation: "Mic", testament: "OT" },
    { order: 34, name: "Nahum", abbreviation: "Nah", testament: "OT" },
    { order: 35, name: "Habakkuk", abbreviation: "Hab", testament: "OT" },
    { order: 36, name: "Zephaniah", abbreviation: "Zeph", testament: "OT" },
    { order: 37, name: "Haggai", abbreviation: "Hag", testament: "OT" },
    { order: 38, name: "Zechariah", abbreviation: "Zech", testament: "OT" },
    { order: 39, name: "Malachi", abbreviation: "Mal", testament: "OT" },
    { order: 40, name: "Matthew", abbreviation: "Matt", testament: "NT" },
    { order: 41, name: "Mark", abbreviation: "Mark", testament: "NT" },
    { order: 42, name: "Luke", abbreviation: "Luke", testament: "NT" },
    { order: 43, name: "John", abbreviation: "John", testament: "NT" },
    { order: 44, name: "Acts", abbreviation: "Acts", testament: "NT" },
    { order: 45, name: "Romans", abbreviation: "Rom", testament: "NT" },
    { order: 46, name: "1 Corinthians", abbreviation: "1Cor", testament: "NT" },
    { order: 47, name: "2 Corinthians", abbreviation: "2Cor", testament: "NT" },
    { order: 48, name: "Galatians", abbreviation: "Gal", testament: "NT" },
    { order: 49, name: "Ephesians", abbreviation: "Eph", testament: "NT" },
    { order: 50, name: "Philippians", abbreviation: "Phil", testament: "NT" },
    { order: 51, name: "Colossians", abbreviation: "Col", testament: "NT" },
    { order: 52, name: "1 Thessalonians", abbreviation: "1Thess", testament: "NT" },
    { order: 53, name: "2 Thessalonians", abbreviation: "2Thess", testament: "NT" },
    { order: 54, name: "1 Timothy", abbreviation: "1Tim", testament: "NT" },
    { order: 55, name: "2 Timothy", abbreviation: "2Tim", testament: "NT" },
    { order: 56, name: "Titus", abbreviation: "Titus", testament: "NT" },
    { order: 57, name: "Philemon", abbreviation: "Phlm", testament: "NT" },
    { order: 58, name: "Hebrews", abbreviation: "Heb", testament: "NT" },
    { order: 59, name: "James", abbreviation: "Jas", testament: "NT" },
    { order: 60, name: "1 Peter", abbreviation: "1Pet", testament: "NT" },
    { order: 61, name: "2 Peter", abbreviation: "2Pet", testament: "NT" },
    { order: 62, name: "1 John", abbreviation: "1John", testament: "NT" },
    { order: 63, name: "2 John", abbreviation: "2John", testament: "NT" },
    { order: 64, name: "3 John", abbreviation: "3John", testament: "NT" },
    { order: 65, name: "Jude", abbreviation: "Jude", testament: "NT" },
    { order: 66, name: "Revelation", abbreviation: "Rev", testament: "NT" }
];

export function getBookDetails(order: number) {
    return BIBLE_BOOKS.find(b => b.order === order);
}
