export const BIBLE_BOOKS = [
    { order: 1, name: "Genesis", abbreviation: "Gen", testament: "OT" },
    { order: 2, name: "Exodus", abbreviation: "Exod", testament: "OT" },
    { order: 3, name: "Leviticus", abbreviation: "Lev", testament: "OT" },
    { order: 4, name: "Numbers", abbreviation: "Num", testament: "OT" },
    { order: 5, name: "Deuteronomy", abbreviation: "Deut", testament: "OT" },
    { order: 6, name: "Joshua", abbreviation: "Josh", testament: "OT" },
    { order: 7, name: "Judges", abbreviation: "Judg", testament: "OT" },
    { order: 8, name: "Ruth", abbreviation: "Ruth", testament: "OT" },
    { order: 9, name: "1 Samuel", abbreviation: "1Sam", testament: "OT" },
    { order: 10, name: "2 Samuel", abbreviation: "2Sam", testament: "OT" },
    { order: 11, name: "1 Kings", abbreviation: "1Kgs", testament: "OT" },
    { order: 12, name: "2 Kings", abbreviation: "2Kgs", testament: "OT" },
    { order: 13, name: "1 Chronicles", abbreviation: "1Chr", testament: "OT" },
    { order: 14, name: "2 Chronicles", abbreviation: "2Chr", testament: "OT" },
    { order: 15, name: "Ezra", abbreviation: "Ezra", testament: "OT" },
    { order: 16, name: "Nehemiah", abbreviation: "Neh", testament: "OT" },
    { order: 17, name: "Esther", abbreviation: "Esth", testament: "OT" },
    { order: 18, name: "Job", abbreviation: "Job", testament: "OT" },
    { order: 19, name: "Psalms", abbreviation: "Ps", testament: "OT" },
    { order: 20, name: "Proverbs", abbreviation: "Prov", testament: "OT" },
    { order: 21, name: "Ecclesiastes", abbreviation: "Eccl", testament: "OT" },
    { order: 22, name: "Song of Solomon", abbreviation: "Song", testament: "OT" },
    { order: 23, name: "Isaiah", abbreviation: "Isa", testament: "OT" },
    { order: 24, name: "Jeremiah", abbreviation: "Jer", testament: "OT" },
    { order: 25, name: "Lamentations", abbreviation: "Lam", testament: "OT" },
    { order: 26, name: "Ezekiel", abbreviation: "Ezek", testament: "OT" },
    { order: 27, name: "Daniel", abbreviation: "Dan", testament: "OT" },
    { order: 28, name: "Hosea", abbreviation: "Hos", testament: "OT" },
    { order: 29, name: "Joel", abbreviation: "Joel", testament: "OT" },
    { order: 30, name: "Amos", abbreviation: "Amos", testament: "OT" },
    { order: 31, name: "Obadiah", abbreviation: "Obad", testament: "OT" },
    { order: 32, name: "Jonah", abbreviation: "Jonah", testament: "OT" },
    { order: 33, name: "Micah", abbreviation: "Mic", testament: "OT" },
    { order: 34, name: "Nahum", abbreviation: "Nah", testament: "OT" },
    { order: 35, name: "Habakkuk", abbreviation: "Hab", testament: "OT" },
    { order: 36, name: "Zephaniah", abbreviation: "Zeph", testament: "OT" },
    { order: 37, name: "Haggai", abbreviation: "Hag", testament: "OT" },
    { order: 38, name: "Zechariah", abbreviation: "Zech", testament: "OT" },
    { order: 39, name: "Malachi", abbreviation: "Mal", testament: "OT" },
    { order: 40, name: "Matthew", abbreviation: "Matt", testament: "NT" },
    { order: 41, name: "Mark", abbreviation: "Mark", testament: "NT" },
    { order: 42, name: "Luke", abbreviation: "Luke", testament: "NT" },
    { order: 43, name: "John", abbreviation: "John", testament: "NT" },
    { order: 44, name: "Acts", abbreviation: "Acts", testament: "NT" },
    { order: 45, name: "Romans", abbreviation: "Rom", testament: "NT" },
    { order: 46, name: "1 Corinthians", abbreviation: "1Cor", testament: "NT" },
    { order: 47, name: "2 Corinthians", abbreviation: "2Cor", testament: "NT" },
    { order: 48, name: "Galatians", abbreviation: "Gal", testament: "NT" },
    { order: 49, name: "Ephesians", abbreviation: "Eph", testament: "NT" },
    { order: 50, name: "Philippians", abbreviation: "Phil", testament: "NT" },
    { order: 51, name: "Colossians", abbreviation: "Col", testament: "NT" },
    { order: 52, name: "1 Thessalonians", abbreviation: "1Thess", testament: "NT" },
    { order: 53, name: "2 Thessalonians", abbreviation: "2Thess", testament: "NT" },
    { order: 54, name: "1 Timothy", abbreviation: "1Tim", testament: "NT" },
    { order: 55, name: "2 Timothy", abbreviation: "2Tim", testament: "NT" },
    { order: 56, name: "Titus", abbreviation: "Titus", testament: "NT" },
    { order: 57, name: "Philemon", abbreviation: "Phlm", testament: "NT" },
    { order: 58, name: "Hebrews", abbreviation: "Heb", testament: "NT" },
    { order: 59, name: "James", abbreviation: "Jas", testament: "NT" },
    { order: 60, name: "1 Peter", abbreviation: "1Pet", testament: "NT" },
    { order: 61, name: "2 Peter", abbreviation: "2Pet", testament: "NT" },
    { order: 62, name: "1 John", abbreviation: "1John", testament: "NT" },
    { order: 63, name: "2 John", abbreviation: "2John", testament: "NT" },
    { order: 64, name: "3 John", abbreviation: "3John", testament: "NT" },
    { order: 65, name: "Jude", abbreviation: "Jude", testament: "NT" },
    { order: 66, name: "Revelation", abbreviation: "Rev", testament: "NT" }
];

export function getBookDetails(order: number) {
    return BIBLE_BOOKS.find(b => b.order === order);
}

/**
 * Canonical Telugu book names keyed by the English book name.
 * Source: పాత నిబంధన + క్రొత్త నిబంధన (Telugu Bible / పవిత్ర గ్రంథము)
 */
export const TELUGU_BOOK_NAMES: Record<string, string> = {
  // Old Testament
  'Genesis':          'ఆదికాండము',
  'Exodus':           'నిర్గమకాండము',
  'Leviticus':        'లేవీయకాండము',
  'Numbers':          'సంఖ్యాకాండము',
  'Deuteronomy':      'ద్వితీయోపదేశకాండము',
  'Joshua':           'యెహోషువ',
  'Judges':           'న్యాయాధిపతులు',
  'Ruth':             'రూతు',
  '1 Samuel':         '1 సమూయేలు',
  '2 Samuel':         '2 సమూయేలు',
  '1 Kings':          '1 రాజులు',
  '2 Kings':          '2 రాజులు',
  '1 Chronicles':     '1 దినవృత్తాంతములు',
  '2 Chronicles':     '2 దినవృత్తాంతములు',
  'Ezra':             'ఎజ్రా',
  'Nehemiah':         'నెహెమ్యా',
  'Esther':           'ఎస్తేరు',
  'Job':              'యోబు',
  'Psalms':           'కీర్తనల గ్రంథము',
  'Proverbs':         'సామెతలు',
  'Ecclesiastes':     'ప్రసంగి',
  'Song of Solomon':  'పరమగీతము',
  'Isaiah':           'యెషయా',
  'Jeremiah':         'యిర్మీయా',
  'Lamentations':     'విలాపవాక్యములు',
  'Ezekiel':          'యెహెజ్కేలు',
  'Daniel':           'దానియేలు',
  'Hosea':            'హోషేయ',
  'Joel':             'యోవేలు',
  'Amos':             'ఆమోసు',
  'Obadiah':          'ఓబద్యా',
  'Jonah':            'యోనా',
  'Micah':            'మీకా',
  'Nahum':            'నహూము',
  'Habakkuk':         'హబక్కూకు',
  'Zephaniah':        'జెఫన్యా',
  'Haggai':           'హగ్గయి',
  'Zechariah':        'జెకర్యా',
  'Malachi':          'మలాకీ',
  // New Testament
  'Matthew':          'మత్తయి',
  'Mark':             'మార్కు',
  'Luke':             'లూకా',
  'John':             'యోహాను',
  'Acts':             'అపొస్తలుల కార్యములు',
  'Romans':           'రోమీయులకు',
  '1 Corinthians':    '1 కొరింథీయులకు',
  '2 Corinthians':    '2 కొరింథీయులకు',
  'Galatians':        'గలతీయులకు',
  'Ephesians':        'ఎఫెసీయులకు',
  'Philippians':      'ఫిలిప్పీయులకు',
  'Colossians':       'కొలొస్సయులకు',
  '1 Thessalonians':  '1 థెస్సలొనీకయులకు',
  '2 Thessalonians':  '2 థెస్సలొనీకయులకు',
  '1 Timothy':        '1 తిమోతికి',
  '2 Timothy':        '2 తిమోతికి',
  'Titus':            'తీతుకు',
  'Philemon':         'ఫిలేమోనుకు',
  'Hebrews':          'హెబ్రీయులకు',
  'James':            'యాకోబు',
  '1 Peter':          '1 పేతురు',
  '2 Peter':          '2 పేతురు',
  '1 John':           '1 యోహాను',
  '2 John':           '2 యోహాను',
  '3 John':           '3 యోహాను',
  'Jude':             'యూదా',
  'Revelation':       'ప్రకటన గ్రంథము',
};

export const HINDI_BOOK_NAMES: Record<string, string> = {
  'Genesis':          'उत्पत्ति',
  'Exodus':           'निर्गमन',
  'Leviticus':        'लैव्यव्यवस्था',
  'Numbers':          'गिनती',
  'Deuteronomy':      'व्यवस्थाविवरण',
  'Joshua':           'यहोशू',
  'Judges':           'न्यायियों',
  'Ruth':             'रूथ',
  '1 Samuel':         '1 शमूएल',
  '2 Samuel':         '2 शमूएल',
  '1 Kings':          '1 राजा',
  '2 Kings':          '2 राजा',
  '1 Chronicles':     '1 इतिहास',
  '2 Chronicles':     '2 इतिहास',
  'Ezra':             'एज्रा',
  'Nehemiah':         'नहेमायाह',
  'Esther':           'एस्तेर',
  'Job':              'अय्यूब',
  'Psalms':           'भजन संहिता',
  'Proverbs':         'नीतिवचन',
  'Ecclesiastes':     'सभोपदेशक',
  'Song of Solomon':  'श्रेष्ठगीत',
  'Isaiah':           'यशायाह',
  'Jeremiah':         'यिर्मयाह',
  'Lamentations':     'विलापगीत',
  'Ezekiel':          'यहेजकेल',
  'Daniel':           'दानिय्येल',
  'Hosea':            'होशे',
  'Joel':             'योएल',
  'Amos':             'आमोस',
  'Obadiah':          'ओबद्याह',
  'Jonah':            'योना',
  'Micah':            'मीका',
  'Nahum':            'नहूम',
  'Habakkuk':         'हबक्कूक',
  'Zephaniah':        'सपन्याह',
  'Haggai':           'हाग्गै',
  'Zechariah':        'जकरयाह',
  'Malachi':          'मलाकी',
  'Matthew':          'मत्ती',
  'Mark':             'मरकुस',
  'Luke':             'लूका',
  'John':             'यूहन्ना',
  'Acts':             'प्रेरितों के काम',
  'Romans':           'रोमियों',
  '1 Corinthians':    '1 कुरिन्थियों',
  '2 Corinthians':    '2 कुरिन्थियों',
  'Galatians':        'गलातियों',
  'Ephesians':        'इफिसियों',
  'Philippians':      'फिलिप्पियों',
  'Colossians':       'कुलुस्सियों',
  '1 Thessalonians':  '1 थिस्सलुनीकियों',
  '2 Thessalonians':  '2 थिस्सलुनीकियों',
  '1 Timothy':        '1 तीमुथियुस',
  '2 Timothy':        '2 तीमुथियुस',
  'Titus':            'तीतुस',
  'Philemon':         'फिलेमोन',
  'Hebrews':          'इब्रानियों',
  'James':            'याकूब',
  '1 Peter':          '1 पतरस',
  '2 Peter':          '2 पतरस',
  '1 John':           '1 यूहन्ना',
  '2 John':           '2 यूहन्ना',
  '3 John':           '3 यूहन्ना',
  'Jude':             'यहूदा',
  'Revelation':       'प्रकाशितवाक्य',
};

/**
 * Given an English book name and a language, returns the localized display name.
 * Falls back to the English name if no mapping exists.
 */
export function getLocalizedBookName(englishName: string, language: string): string {
  const cleanLang = (language || '').toLowerCase().trim();
  if (cleanLang === 'telugu' || cleanLang === 'te') {
    return TELUGU_BOOK_NAMES[englishName] ?? englishName;
  }
  if (cleanLang === 'hindi' || cleanLang === 'hi') {
    return HINDI_BOOK_NAMES[englishName] ?? englishName;
  }
  return englishName;
}



